[context.deploy-preview.environment]
  HUGO_VERSION = "0.20"

[context.production.environment]
  HUGO_VERSION = "0.21"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"
