baseurl = "https://www.nagibtharani.com/"
languageCode = "en-us"
title = "Nagib Tharani"
disqusShortname = "ntharani"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Nagib Tharani"
	description = "My Personal Website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []
	organization_image = "logo.png"

[params.social]
	twitter = "nagibtharani"
	author = "nagibtharani"
	facebook_admin = ""
	facebook_author = "nagib.tharani"
	facebook = "nagib.tharani"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
